import { env, requireEnv } from '../../src/config.mjs';
import { sleep } from '../../src/util/http.mjs';
import { warn } from '../../src/util/log.mjs';
import { INSTAGRAM_TOKEN_FILE, readJson } from './paths.mjs';

// v25.0 is what the current content-publishing docs show. graph.instagram.com is the host for a
// token obtained through Instagram Login; a Facebook-Login token talks to graph.facebook.com
// instead, hence the override.
const VERSION = () => env.INSTAGRAM_API_VERSION || 'v25.0';
const HOST = () => env.INSTAGRAM_API_HOST || 'graph.instagram.com';

export const base = () => `https://${HOST()}/${VERSION()}`;

/**
 * The user id and the token that is actually current.
 *
 * .env holds the token generated by hand in the Meta dashboard. refresh_token.mjs writes a newer
 * one to state, and that one wins while it is still valid - otherwise an unattended sync would
 * quietly stop working 60 days after setup, which is exactly when nobody is watching.
 */
export function credentials() {
  const [userId, envToken] = requireEnv('INSTAGRAM_USER_ID', 'INSTAGRAM_ACCESS_TOKEN');
  const stored = readJson(INSTAGRAM_TOKEN_FILE);
  if (stored && stored.access_token && Date.parse(stored.expires_at) > Date.now()) {
    return [userId, stored.access_token];
  }
  if (stored && stored.access_token) {
    warn('The refreshed Instagram token in state/ has expired; falling back to the one in .env.');
  }
  return [userId, envToken];
}

// Long-lived tokens last 60 days and can be exchanged for a fresh one any time after 24 hours.
// The endpoint sits at the host root rather than under a version.
export async function refreshLongLivedToken(token) {
  const url =
    `https://${HOST()}/refresh_access_token?grant_type=ig_refresh_token` +
    `&access_token=${encodeURIComponent(token)}`;
  const res = await fetch(url);
  const body = await res.json();
  if (!res.ok) throw new InstagramError(res.status, body);
  return body;
}

/**
 * Meta answers with a number and a sentence written for somebody who already knows what went
 * wrong. These are the causes worth checking first; the raw message is always printed alongside,
 * because this list is a shortcut and not a substitute for it.
 */
const ERROR_HINTS = {
  4: 'Application request limit reached. Wait for the window to move; do not retry in a loop.',
  9: 'Instagram has action-blocked the account for posting too often. This is about the account, ' +
    'not the app: it lifts itself after several hours to a day. Retrying into it makes it longer.',
  10: 'Permission missing. instagram_business_content_publish has to be granted AND approved in App Review.',
  17: 'User request limit reached.',
  32: 'Page-level throttling. Too many calls in a short window.',
  190: 'Access token invalid or expired. Long-lived tokens die after 60 days - refresh it in the Meta dashboard.',
  200: 'Permission error. Usually the same cause as 10, or the account is not a Business account.',
  613: 'Calls per second exceeded. Increase --pause.',
  9004: 'Instagram could not fetch the media from the URL. It has to be publicly reachable, with no redirect and no auth.',
  2207003: 'Media could not be downloaded. Check the URL from a browser with no session.',
  2207020: 'Media fetch failed - the URL is unreachable, or the object is not public.',
  2207026: 'Video format not supported. Reels want H.264/AAC in an MP4 container.',
  2207050: 'Container not finished. Publishing was attempted before the upload had processed.',
  2207051: 'Instagram classified the post as spam. Vary the caption, and slow the backfill down.',
  2207057: 'Aspect ratio outside the accepted range.',
};

export function explainError(body) {
  const err = (body && body.error) || {};
  const parts = [];
  if (err.message) parts.push(err.message);
  const hint = ERROR_HINTS[err.code] || ERROR_HINTS[err.error_subcode];
  if (hint) parts.push('-> ' + hint);
  if (err.code) {
    parts.push(
      `(code ${err.code}${err.error_subcode ? ', subcode ' + err.error_subcode : ''}; ` +
        'reference: developers.facebook.com/docs/instagram-platform/reference/error-codes)'
    );
  }
  return parts.join('\n     ') || JSON.stringify(body);
}

export class InstagramError extends Error {
  constructor(status, body) {
    super(`Instagram HTTP ${status}\n     ${explainError(body)}`);
    this.name = 'InstagramError';
    this.status = status;
    this.body = body;
    this.code = body && body.error ? body.error.code : undefined;
  }
}

async function call(method, path, params, attempt = 0) {
  const url = new URL(base() + path);
  const options = { method };

  if (method === 'GET') {
    for (const [k, v] of Object.entries(params)) url.searchParams.set(k, String(v));
  } else {
    options.headers = { 'Content-Type': 'application/x-www-form-urlencoded' };
    options.body = new URLSearchParams(params).toString();
  }

  // Repeating a lost request is only safe when repeating it cannot create something. A GET and a
  // container creation qualify; media_publish does not - if the request arrived and only the reply
  // was lost, a retry posts the same thing twice, and Instagram has no way to tell us apart.
  const repeatable = method === 'GET' || !path.endsWith('/media_publish');

  let res;
  try {
    res = await fetch(url.toString(), options);
  } catch (err) {
    // A dropped connection over a two-hour run is normal, not exceptional.
    if (repeatable && attempt < 3) {
      const backoff = 5000 * 2 ** attempt;
      warn(`Network error talking to Instagram (${err.message}). Retrying in ${backoff / 1000}s.`);
      await sleep(backoff);
      return call(method, path, params, attempt + 1);
    }
    const wrapped = new Error(
      `Network error on ${method} ${path}: ${err.message}` +
        (repeatable ? '' : '\n     This was the publish call. It may or may not have gone through - ' +
          'check the account before re-running, and add the post to state/posted.json if it is there.')
    );
    wrapped.networkFailure = true;
    wrapped.duringPublish = !repeatable;
    throw wrapped;
  }

  const text = await res.text();
  let body = text;
  try {
    body = text ? JSON.parse(text) : null;
  } catch {
    /* keep the raw text for the error */
  }

  if (res.ok) return body;

  // A 5xx is Meta having a moment and is worth retrying. A 4xx is a decision - the token, the
  // permission or the media is wrong - and retrying it just repeats the same mistake.
  if (res.status >= 500 && attempt < 3) {
    const backoff = 2000 * 2 ** attempt;
    warn(`Instagram returned ${res.status}. Retrying in ${backoff / 1000}s.`);
    await sleep(backoff);
    return call(method, path, params, attempt + 1);
  }

  throw new InstagramError(res.status, body);
}

export const post = (path, params) => call('POST', path, params);
export const get = (path, params) => call('GET', path, params);

/**
 * How many of the 100 posts in the moving 24-hour window are already spent.
 *
 * Asking is better than counting locally: posts made from the phone count too, and a backfill that
 * assumed it had the whole quota would hit the wall halfway through.
 */
export async function publishingLimit(userId, token) {
  const body = await get(`/${userId}/content_publishing_limit`, {
    fields: 'config,quota_usage',
    access_token: token,
  });
  const row = (body && body.data && body.data[0]) || {};
  return {
    used: row.quota_usage ?? 0,
    total: (row.config && row.config.quota_total) ?? 100,
  };
}

// Instagram downloads and transcodes before it will publish. Publishing early returns "media not
// ready" rather than waiting, so the container has to be polled until it says FINISHED.
export async function waitForContainer(containerId, token, { timeoutMs = 5 * 60 * 1000 } = {}) {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    const status = await get(`/${containerId}`, { fields: 'status_code,status', access_token: token });
    if (status.status_code === 'FINISHED') return status;
    if (status.status_code === 'ERROR' || status.status_code === 'EXPIRED') {
      throw new Error(`Container ${containerId} came back ${status.status_code}: ${status.status || 'no detail'}`);
    }
    await sleep(5000);
  }
  throw new Error(`Container ${containerId} was still not FINISHED after ${timeoutMs / 1000}s.`);
}
