/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE IF NOT EXISTS `ASSET` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `assetMetaFileHint` varchar(255) DEFAULT NULL,
  `internalName` varchar(255) DEFAULT NULL,
  `unityAssetGuid` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4;

DELETE FROM `ASSET`;
/*!40000 ALTER TABLE `ASSET` DISABLE KEYS */;
INSERT INTO `ASSET` (`id`, `assetMetaFileHint`, `internalName`, `unityAssetGuid`) VALUES
	(1, 'C:\\dev\\projects\\razarion\\razarion-media\\unity\\razarion\\Assets\\Vehicles Constructor.meta', 'Vehicles Constructor', '0603ae7aaa099224198c5febaebb9559');
/*!40000 ALTER TABLE `ASSET` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
