/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE IF NOT EXISTS `BASE_ITEM_DEMOLITION_STEP_EFFECT_PARTICLE` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `positionX` double DEFAULT NULL,
  `positionY` double DEFAULT NULL,
  `positionZ` double DEFAULT NULL,
  `demolitionStepEffect` int(11) NOT NULL,
  `orderColumn` int(11) DEFAULT NULL,
  `particle_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK5y84j4v1h2w5xe21gmu4vda0k` (`demolitionStepEffect`),
  KEY `FKltsssj4p9edvh4a1yu34uvhc9` (`particle_id`),
  CONSTRAINT `FK5y84j4v1h2w5xe21gmu4vda0k` FOREIGN KEY (`demolitionStepEffect`) REFERENCES `BASE_ITEM_DEMOLITION_STEP_EFFECT` (`id`),
  CONSTRAINT `FKltsssj4p9edvh4a1yu34uvhc9` FOREIGN KEY (`particle_id`) REFERENCES `PARTICLE_EMITTER_SEQUENCE` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DELETE FROM `BASE_ITEM_DEMOLITION_STEP_EFFECT_PARTICLE`;
/*!40000 ALTER TABLE `BASE_ITEM_DEMOLITION_STEP_EFFECT_PARTICLE` DISABLE KEYS */;
/*!40000 ALTER TABLE `BASE_ITEM_DEMOLITION_STEP_EFFECT_PARTICLE` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
