/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE IF NOT EXISTS `BASE_ITEM_BUILDER_TYPE_ABLE_TO_BUILD` (
  `builder` int(11) NOT NULL,
  `baseItemType` int(11) NOT NULL,
  UNIQUE KEY `UK_iilyj6hka733l0r6fe21q3imu` (`baseItemType`),
  KEY `FK28k6bigopln9kqkqspxgf45wo` (`builder`),
  CONSTRAINT `FK28k6bigopln9kqkqspxgf45wo` FOREIGN KEY (`builder`) REFERENCES `BASE_ITEM_BUILDER_TYPE` (`id`),
  CONSTRAINT `FKt42sflt3ub3tu41rcqgysx4h5` FOREIGN KEY (`baseItemType`) REFERENCES `BASE_ITEM_TYPE` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DELETE FROM `BASE_ITEM_BUILDER_TYPE_ABLE_TO_BUILD`;
/*!40000 ALTER TABLE `BASE_ITEM_BUILDER_TYPE_ABLE_TO_BUILD` DISABLE KEYS */;
INSERT INTO `BASE_ITEM_BUILDER_TYPE_ABLE_TO_BUILD` (`builder`, `baseItemType`) VALUES
	(1, 4),
	(1, 6),
	(1, 7),
	(1, 11),
	(1, 21),
	(2, 5),
	(2, 9),
	(2, 14),
	(2, 15),
	(2, 17),
	(2, 22);
/*!40000 ALTER TABLE `BASE_ITEM_BUILDER_TYPE_ABLE_TO_BUILD` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
