/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE IF NOT EXISTS `BASE_ITEM_FACTORY_TYPE_ABLE_TO_BUILD` (
  `factory` int(11) NOT NULL,
  `baseItemType` int(11) NOT NULL,
  UNIQUE KEY `UK_s56cdvc3hq6y8o7r2gsrfu52c` (`baseItemType`),
  KEY `FKtc6hh437se4nqa2g9tmmg4na5` (`factory`),
  CONSTRAINT `FKlfyjj2uwgsatdw7ux1wds5t7x` FOREIGN KEY (`baseItemType`) REFERENCES `BASE_ITEM_TYPE` (`id`),
  CONSTRAINT `FKtc6hh437se4nqa2g9tmmg4na5` FOREIGN KEY (`factory`) REFERENCES `BASE_ITEM_FACTORY_TYPE` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DELETE FROM `BASE_ITEM_FACTORY_TYPE_ABLE_TO_BUILD`;
/*!40000 ALTER TABLE `BASE_ITEM_FACTORY_TYPE_ABLE_TO_BUILD` DISABLE KEYS */;
INSERT INTO `BASE_ITEM_FACTORY_TYPE_ABLE_TO_BUILD` (`factory`, `baseItemType`) VALUES
	(1, 1),
	(1, 2),
	(1, 3),
	(2, 10),
	(3, 12),
	(3, 18),
	(4, 8),
	(4, 13),
	(4, 16),
	(4, 20);
/*!40000 ALTER TABLE `BASE_ITEM_FACTORY_TYPE_ABLE_TO_BUILD` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
