/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE IF NOT EXISTS `BASE_ITEM_WEAPON_TYPE_DISALLOWED_ITEM_TYPES` (
  `weapon` int(11) NOT NULL,
  `baseItemType` int(11) NOT NULL,
  UNIQUE KEY `UK_amlxea599glsjiee8ukxv7rj9` (`baseItemType`),
  KEY `FKslr6g6v2qqyxtt9dmc09ftrar` (`weapon`),
  CONSTRAINT `FK7jeslr1x745ry5ybx4agf1kte` FOREIGN KEY (`baseItemType`) REFERENCES `BASE_ITEM_TYPE` (`id`),
  CONSTRAINT `FKslr6g6v2qqyxtt9dmc09ftrar` FOREIGN KEY (`weapon`) REFERENCES `BASE_ITEM_WEAPON_TYPE` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DELETE FROM `BASE_ITEM_WEAPON_TYPE_DISALLOWED_ITEM_TYPES`;
/*!40000 ALTER TABLE `BASE_ITEM_WEAPON_TYPE_DISALLOWED_ITEM_TYPES` DISABLE KEYS */;
/*!40000 ALTER TABLE `BASE_ITEM_WEAPON_TYPE_DISALLOWED_ITEM_TYPES` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
