/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE IF NOT EXISTS `BOT_SCENE_CONFLICT_CONFIG` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `enterDuration` int(11) NOT NULL,
  `enterKills` int(11) NOT NULL,
  `leaveNoKillDuration` int(11) NOT NULL,
  `maxDistance` double NOT NULL,
  `minDistance` double NOT NULL,
  `rePopMillis` int(11) DEFAULT NULL,
  `stopKills` int(11) DEFAULT NULL,
  `stopMillis` int(11) DEFAULT NULL,
  `botConfig_id` int(11) DEFAULT NULL,
  `targetBaseItemType_id` int(11) DEFAULT NULL,
  `botConfig` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FKsa7ypi28v52meu8c3le2nwaom` (`botConfig_id`),
  KEY `FKlma4qi8pwcrif0ckup8rxrya7` (`targetBaseItemType_id`),
  KEY `FKeiobef7r4fmbjbxa1pghslhvm` (`botConfig`),
  CONSTRAINT `FKeiobef7r4fmbjbxa1pghslhvm` FOREIGN KEY (`botConfig`) REFERENCES `BOT_SCENE_CONFIG` (`id`),
  CONSTRAINT `FKlma4qi8pwcrif0ckup8rxrya7` FOREIGN KEY (`targetBaseItemType_id`) REFERENCES `BASE_ITEM_TYPE` (`id`),
  CONSTRAINT `FKsa7ypi28v52meu8c3le2nwaom` FOREIGN KEY (`botConfig_id`) REFERENCES `BOT_CONFIG` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DELETE FROM `BOT_SCENE_CONFLICT_CONFIG`;
/*!40000 ALTER TABLE `BOT_SCENE_CONFLICT_CONFIG` DISABLE KEYS */;
/*!40000 ALTER TABLE `BOT_SCENE_CONFLICT_CONFIG` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
