/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE IF NOT EXISTS `BOT_SCENE_CONFIG_BOTS_TO_WATCH` (
  `botScene` int(11) NOT NULL,
  `bot` int(11) NOT NULL,
  UNIQUE KEY `UK_n11vrd5hv42ih8gs7oca20ftc` (`bot`),
  KEY `FKaqf9ms83ch45310assmbd7k33` (`botScene`),
  CONSTRAINT `FKaqf9ms83ch45310assmbd7k33` FOREIGN KEY (`botScene`) REFERENCES `BOT_SCENE_CONFIG` (`id`),
  CONSTRAINT `FKkf6g9dgv0g5v2w4g07bhjpp58` FOREIGN KEY (`bot`) REFERENCES `BOT_CONFIG` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DELETE FROM `BOT_SCENE_CONFIG_BOTS_TO_WATCH`;
/*!40000 ALTER TABLE `BOT_SCENE_CONFIG_BOTS_TO_WATCH` DISABLE KEYS */;
/*!40000 ALTER TABLE `BOT_SCENE_CONFIG_BOTS_TO_WATCH` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
