/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE IF NOT EXISTS `BOT_CONFIG_ENRAGEMENT_STATE_CONFIG` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `enrageUpKills` int(11) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `botConfig` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK8cnda4p93imbirpidwrfoq27n` (`botConfig`),
  CONSTRAINT `FK8cnda4p93imbirpidwrfoq27n` FOREIGN KEY (`botConfig`) REFERENCES `BOT_CONFIG` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=132 DEFAULT CHARSET=utf8mb4;

DELETE FROM `BOT_CONFIG_ENRAGEMENT_STATE_CONFIG`;
/*!40000 ALTER TABLE `BOT_CONFIG_ENRAGEMENT_STATE_CONFIG` DISABLE KEYS */;
INSERT INTO `BOT_CONFIG_ENRAGEMENT_STATE_CONFIG` (`id`, `enrageUpKills`, `name`, `botConfig`) VALUES
	(30, NULL, NULL, 31),
	(127, NULL, 'Normal', 133),
	(128, NULL, NULL, 134),
	(129, NULL, NULL, 135),
	(130, NULL, NULL, 136),
	(131, NULL, NULL, 137);
/*!40000 ALTER TABLE `BOT_CONFIG_ENRAGEMENT_STATE_CONFIG` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
