/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE IF NOT EXISTS `BOX_ITEM_TYPE_POSSIBILITY` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `crystals` int(11) DEFAULT NULL,
  `possibility` double NOT NULL,
  `inventoryItem_id` int(11) DEFAULT NULL,
  `boxItemTypePossibilities_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FKo3e4s038xiegu5lp08ts2vbda` (`inventoryItem_id`),
  KEY `FK94mqsdrnx85779a7i1de17db6` (`boxItemTypePossibilities_id`),
  CONSTRAINT `FK94mqsdrnx85779a7i1de17db6` FOREIGN KEY (`boxItemTypePossibilities_id`) REFERENCES `BOX_ITEM_TYPE` (`id`),
  CONSTRAINT `FKo3e4s038xiegu5lp08ts2vbda` FOREIGN KEY (`inventoryItem_id`) REFERENCES `INVENTORY_ITEM` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=31 DEFAULT CHARSET=utf8mb4;

DELETE FROM `BOX_ITEM_TYPE_POSSIBILITY`;
/*!40000 ALTER TABLE `BOX_ITEM_TYPE_POSSIBILITY` DISABLE KEYS */;
INSERT INTO `BOX_ITEM_TYPE_POSSIBILITY` (`id`, `crystals`, `possibility`, `inventoryItem_id`, `boxItemTypePossibilities_id`) VALUES
	(27, NULL, 0.5, 2, 3),
	(28, 2, 1, NULL, 3),
	(29, NULL, 1, 1, 1),
	(30, 1, 1, NULL, 2);
/*!40000 ALTER TABLE `BOX_ITEM_TYPE_POSSIBILITY` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
