/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE IF NOT EXISTS `PARTICLE_SYSTEM_EMITTER_MESH_PATH` (
  `particleSystem` int(11) NOT NULL,
  `emitterMeshPath` varchar(255) DEFAULT NULL,
  `orderColumn` int(11) NOT NULL,
  PRIMARY KEY (`particleSystem`,`orderColumn`),
  CONSTRAINT `FKbdxodt0pvh8lopiwwrkns2q1y` FOREIGN KEY (`particleSystem`) REFERENCES `PARTICLE_SYSTEM` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DELETE FROM `PARTICLE_SYSTEM_EMITTER_MESH_PATH`;
/*!40000 ALTER TABLE `PARTICLE_SYSTEM_EMITTER_MESH_PATH` DISABLE KEYS */;
INSERT INTO `PARTICLE_SYSTEM_EMITTER_MESH_PATH` (`particleSystem`, `emitterMeshPath`, `orderColumn`) VALUES
	(1, 'Cannon00 \'41\'', 0),
	(1, 'Cannon00 \'41\'.Cannon00', 1);
/*!40000 ALTER TABLE `PARTICLE_SYSTEM_EMITTER_MESH_PATH` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
