/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE IF NOT EXISTS `PARTICLE_SYSTEM` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `internalName` varchar(255) DEFAULT NULL,
  `threeJsModelConfig_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FKkhklfqlsgjel77t2x1ame1xp6` (`threeJsModelConfig_id`),
  CONSTRAINT `FKkhklfqlsgjel77t2x1ame1xp6` FOREIGN KEY (`threeJsModelConfig_id`) REFERENCES `THREE_JS_MODEL` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4;

DELETE FROM `PARTICLE_SYSTEM`;
/*!40000 ALTER TABLE `PARTICLE_SYSTEM` DISABLE KEYS */;
INSERT INTO `PARTICLE_SYSTEM` (`id`, `internalName`, `threeJsModelConfig_id`) VALUES
	(1, 'Buildup Beam', 50),
	(2, 'Viper Muzzle', 51);
/*!40000 ALTER TABLE `PARTICLE_SYSTEM` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
