/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE IF NOT EXISTS `PLANET_LIMITATION` (
  `PlanetEntity_id` int(11) NOT NULL,
  `itemTypeLimitation` int(11) DEFAULT NULL,
  `baseItemTypeEntityId` int(11) NOT NULL,
  PRIMARY KEY (`PlanetEntity_id`,`baseItemTypeEntityId`),
  KEY `FKmnjiyn3ivehnao6o5fuj4qdwc` (`baseItemTypeEntityId`),
  CONSTRAINT `FKmnjiyn3ivehnao6o5fuj4qdwc` FOREIGN KEY (`baseItemTypeEntityId`) REFERENCES `BASE_ITEM_TYPE` (`id`),
  CONSTRAINT `FKmv1lgmud5v7ja4eyakk2sgdi5` FOREIGN KEY (`PlanetEntity_id`) REFERENCES `PLANET` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DELETE FROM `PLANET_LIMITATION`;
/*!40000 ALTER TABLE `PLANET_LIMITATION` DISABLE KEYS */;
INSERT INTO `PLANET_LIMITATION` (`PlanetEntity_id`, `itemTypeLimitation`, `baseItemTypeEntityId`) VALUES
	(117, 2, 1),
	(117, 3, 2),
	(117, 20, 3),
	(117, 4, 4);
/*!40000 ALTER TABLE `PLANET_LIMITATION` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
