/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE IF NOT EXISTS `QUEST_COMPARISON_BASE_ITEM` (
  `ComparisonConfigEntity_id` int(11) NOT NULL,
  `typeCount` int(11) DEFAULT NULL,
  `baseItemTypeEntityId` int(11) NOT NULL,
  PRIMARY KEY (`ComparisonConfigEntity_id`,`baseItemTypeEntityId`),
  KEY `FKox69d9d2u7iegll4y4bua3uhn` (`baseItemTypeEntityId`),
  CONSTRAINT `FKox69d9d2u7iegll4y4bua3uhn` FOREIGN KEY (`baseItemTypeEntityId`) REFERENCES `BASE_ITEM_TYPE` (`id`),
  CONSTRAINT `FKqewsitlqloonk59cl0vlbyq6o` FOREIGN KEY (`ComparisonConfigEntity_id`) REFERENCES `QUEST_COMPARISON` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DELETE FROM `QUEST_COMPARISON_BASE_ITEM`;
/*!40000 ALTER TABLE `QUEST_COMPARISON_BASE_ITEM` DISABLE KEYS */;
INSERT INTO `QUEST_COMPARISON_BASE_ITEM` (`ComparisonConfigEntity_id`, `typeCount`, `baseItemTypeEntityId`) VALUES
	(15, 1, 4),
	(16, 3, 3);
/*!40000 ALTER TABLE `QUEST_COMPARISON_BASE_ITEM` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
