/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE IF NOT EXISTS `QUEST_COMPARISON_BOT` (
  `comparisonConfig` int(11) NOT NULL,
  `botConfig` int(11) NOT NULL,
  KEY `FKgsivij4a6t882dkggs8ubbgay` (`botConfig`),
  KEY `FKk49fh7nqm3yx2jbu9088qh4pn` (`comparisonConfig`),
  CONSTRAINT `FKgsivij4a6t882dkggs8ubbgay` FOREIGN KEY (`botConfig`) REFERENCES `BOT_CONFIG` (`id`),
  CONSTRAINT `FKk49fh7nqm3yx2jbu9088qh4pn` FOREIGN KEY (`comparisonConfig`) REFERENCES `QUEST_COMPARISON` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DELETE FROM `QUEST_COMPARISON_BOT`;
/*!40000 ALTER TABLE `QUEST_COMPARISON_BOT` DISABLE KEYS */;
/*!40000 ALTER TABLE `QUEST_COMPARISON_BOT` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
