/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE IF NOT EXISTS `SCENE_BOT_REMOVE_OWN_ITEMS_COMMAND` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `botAuxiliaryIdId` int(11) DEFAULT NULL,
  `baseItemType2Remove_id` int(11) DEFAULT NULL,
  `botRemoveOwnItemCommandEntities_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FKd5rbur518hugollv8v21jnj1o` (`baseItemType2Remove_id`),
  KEY `FKhdrkr0eixuks1uoe9t9c949j3` (`botRemoveOwnItemCommandEntities_id`),
  CONSTRAINT `FKd5rbur518hugollv8v21jnj1o` FOREIGN KEY (`baseItemType2Remove_id`) REFERENCES `BASE_ITEM_TYPE` (`id`),
  CONSTRAINT `FKhdrkr0eixuks1uoe9t9c949j3` FOREIGN KEY (`botRemoveOwnItemCommandEntities_id`) REFERENCES `SCENE` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DELETE FROM `SCENE_BOT_REMOVE_OWN_ITEMS_COMMAND`;
/*!40000 ALTER TABLE `SCENE_BOT_REMOVE_OWN_ITEMS_COMMAND` DISABLE KEYS */;
/*!40000 ALTER TABLE `SCENE_BOT_REMOVE_OWN_ITEMS_COMMAND` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
