/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE IF NOT EXISTS `SCENE_BOT_MOVE_COMMAND` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `botAuxiliaryIdId` int(11) DEFAULT NULL,
  `targetPositionX` double DEFAULT NULL,
  `targetPositionY` double DEFAULT NULL,
  `baseItemType_id` int(11) DEFAULT NULL,
  `botMoveCommandEntities_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FKhh30m3n5y5yy51iiodrfjgxj5` (`baseItemType_id`),
  KEY `FKo130arf1f906t656xu20lrd3l` (`botMoveCommandEntities_id`),
  CONSTRAINT `FKhh30m3n5y5yy51iiodrfjgxj5` FOREIGN KEY (`baseItemType_id`) REFERENCES `BASE_ITEM_TYPE` (`id`),
  CONSTRAINT `FKo130arf1f906t656xu20lrd3l` FOREIGN KEY (`botMoveCommandEntities_id`) REFERENCES `SCENE` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DELETE FROM `SCENE_BOT_MOVE_COMMAND`;
/*!40000 ALTER TABLE `SCENE_BOT_MOVE_COMMAND` DISABLE KEYS */;
/*!40000 ALTER TABLE `SCENE_BOT_MOVE_COMMAND` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
