/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE IF NOT EXISTS `SCENE_RESOURCE_ITEM_POSITION` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `x` double NOT NULL,
  `y` double NOT NULL,
  `rotationZ` double NOT NULL,
  `resourceItemType_id` int(11) DEFAULT NULL,
  `sceneId` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FKb59khrjqywtrlb7k5awklv5sg` (`resourceItemType_id`),
  KEY `FKdwjv6d2ofmaqenv5c9ahsjowh` (`sceneId`),
  CONSTRAINT `FKb59khrjqywtrlb7k5awklv5sg` FOREIGN KEY (`resourceItemType_id`) REFERENCES `RESOURCE_ITEM_TYPE` (`id`),
  CONSTRAINT `FKdwjv6d2ofmaqenv5c9ahsjowh` FOREIGN KEY (`sceneId`) REFERENCES `SCENE` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8mb4;

DELETE FROM `SCENE_RESOURCE_ITEM_POSITION`;
/*!40000 ALTER TABLE `SCENE_RESOURCE_ITEM_POSITION` DISABLE KEYS */;
INSERT INTO `SCENE_RESOURCE_ITEM_POSITION` (`id`, `x`, `y`, `rotationZ`, `resourceItemType_id`, `sceneId`) VALUES
	(18, 200, 120, 0, 1, 183);
/*!40000 ALTER TABLE `SCENE_RESOURCE_ITEM_POSITION` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
