/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE IF NOT EXISTS `SCENE_START_POINT_PLACER` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `enemyFreeRadius` double DEFAULT NULL,
  `suggestedPositionX` double DEFAULT NULL,
  `suggestedPositionY` double DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4;

DELETE FROM `SCENE_START_POINT_PLACER`;
/*!40000 ALTER TABLE `SCENE_START_POINT_PLACER` DISABLE KEYS */;
INSERT INTO `SCENE_START_POINT_PLACER` (`id`, `enemyFreeRadius`, `suggestedPositionX`, `suggestedPositionY`) VALUES
	(1, 1, NULL, NULL);
/*!40000 ALTER TABLE `SCENE_START_POINT_PLACER` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
