/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE IF NOT EXISTS `SCENE_BOT_KILL_OTHER_BOT_COMMAND` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `botAuxiliaryIdId` int(11) DEFAULT NULL,
  `dominanceFactor` int(11) NOT NULL,
  `targetBotAuxiliaryIdId` int(11) DEFAULT NULL,
  `attackerBaseItemType_id` int(11) DEFAULT NULL,
  `spawnPoint_id` int(11) DEFAULT NULL,
  `botKillOtherBotCommandEntities_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FKckvfx8kt348yfb5d8txret8c1` (`attackerBaseItemType_id`),
  KEY `FKsl1rsgx936c34qyovbws0otae` (`spawnPoint_id`),
  KEY `FKbb3b9ari50ovnnpvjv3mevis4` (`botKillOtherBotCommandEntities_id`),
  CONSTRAINT `FKbb3b9ari50ovnnpvjv3mevis4` FOREIGN KEY (`botKillOtherBotCommandEntities_id`) REFERENCES `SCENE` (`id`),
  CONSTRAINT `FKckvfx8kt348yfb5d8txret8c1` FOREIGN KEY (`attackerBaseItemType_id`) REFERENCES `BASE_ITEM_TYPE` (`id`),
  CONSTRAINT `FKsl1rsgx936c34qyovbws0otae` FOREIGN KEY (`spawnPoint_id`) REFERENCES `PLACE_CONFIG` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DELETE FROM `SCENE_BOT_KILL_OTHER_BOT_COMMAND`;
/*!40000 ALTER TABLE `SCENE_BOT_KILL_OTHER_BOT_COMMAND` DISABLE KEYS */;
/*!40000 ALTER TABLE `SCENE_BOT_KILL_OTHER_BOT_COMMAND` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
