/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE IF NOT EXISTS `SCENE_BOT_KILL_HUMAN_COMMAND` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `botAuxiliaryIdId` int(11) DEFAULT NULL,
  `dominanceFactor` int(11) NOT NULL,
  `attackerBaseItemType_id` int(11) DEFAULT NULL,
  `spawnPoint_id` int(11) DEFAULT NULL,
  `botKillHumanCommandEntities_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FKqdgvd8bc4gqifn5d46rmf5iy8` (`attackerBaseItemType_id`),
  KEY `FKdyqi8q4nrjqpcu4r9oiahw264` (`spawnPoint_id`),
  KEY `FKptfyx1wxu2fyxkg6nbj0xwec` (`botKillHumanCommandEntities_id`),
  CONSTRAINT `FKdyqi8q4nrjqpcu4r9oiahw264` FOREIGN KEY (`spawnPoint_id`) REFERENCES `PLACE_CONFIG` (`id`),
  CONSTRAINT `FKptfyx1wxu2fyxkg6nbj0xwec` FOREIGN KEY (`botKillHumanCommandEntities_id`) REFERENCES `SCENE` (`id`),
  CONSTRAINT `FKqdgvd8bc4gqifn5d46rmf5iy8` FOREIGN KEY (`attackerBaseItemType_id`) REFERENCES `BASE_ITEM_TYPE` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DELETE FROM `SCENE_BOT_KILL_HUMAN_COMMAND`;
/*!40000 ALTER TABLE `SCENE_BOT_KILL_HUMAN_COMMAND` DISABLE KEYS */;
/*!40000 ALTER TABLE `SCENE_BOT_KILL_HUMAN_COMMAND` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
