/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE IF NOT EXISTS `SCENE_BOT_ATTACK_COMMAND` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `botAuxiliaryIdId` int(11) DEFAULT NULL,
  `actorItemType_id` int(11) DEFAULT NULL,
  `targetItemType_id` int(11) DEFAULT NULL,
  `targetSelection_id` int(11) DEFAULT NULL,
  `botAttackCommandEntities_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK41qgg36def0x3j8xjg61tl9ly` (`actorItemType_id`),
  KEY `FK9q1onf1n6vq18ep096s80u0vm` (`targetItemType_id`),
  KEY `FK6lfeos35sq8euepu1nqeoijqq` (`targetSelection_id`),
  KEY `FKrgg9j7lq38k61hkwuy73wxght` (`botAttackCommandEntities_id`),
  CONSTRAINT `FK41qgg36def0x3j8xjg61tl9ly` FOREIGN KEY (`actorItemType_id`) REFERENCES `BASE_ITEM_TYPE` (`id`),
  CONSTRAINT `FK6lfeos35sq8euepu1nqeoijqq` FOREIGN KEY (`targetSelection_id`) REFERENCES `PLACE_CONFIG` (`id`),
  CONSTRAINT `FK9q1onf1n6vq18ep096s80u0vm` FOREIGN KEY (`targetItemType_id`) REFERENCES `BASE_ITEM_TYPE` (`id`),
  CONSTRAINT `FKrgg9j7lq38k61hkwuy73wxght` FOREIGN KEY (`botAttackCommandEntities_id`) REFERENCES `SCENE` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DELETE FROM `SCENE_BOT_ATTACK_COMMAND`;
/*!40000 ALTER TABLE `SCENE_BOT_ATTACK_COMMAND` DISABLE KEYS */;
/*!40000 ALTER TABLE `SCENE_BOT_ATTACK_COMMAND` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
