/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE IF NOT EXISTS `SCENE_BOT_HARVEST_COMMAND` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `botAuxiliaryIdId` int(11) DEFAULT NULL,
  `harvesterItemType_id` int(11) DEFAULT NULL,
  `resourceItemType_id` int(11) DEFAULT NULL,
  `resourceSelection_id` int(11) DEFAULT NULL,
  `botHarvestCommandEntities_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK52rh3hg6sc1g6xuhxqd6l0l0w` (`harvesterItemType_id`),
  KEY `FK9sc5qi93p4cby5b2hojcr90gh` (`resourceItemType_id`),
  KEY `FKs2dv4bd53e7r6vokmm96qh0x4` (`resourceSelection_id`),
  KEY `FK3mpduff9ibnr01pj8lnbnetm1` (`botHarvestCommandEntities_id`),
  CONSTRAINT `FK3mpduff9ibnr01pj8lnbnetm1` FOREIGN KEY (`botHarvestCommandEntities_id`) REFERENCES `SCENE` (`id`),
  CONSTRAINT `FK52rh3hg6sc1g6xuhxqd6l0l0w` FOREIGN KEY (`harvesterItemType_id`) REFERENCES `BASE_ITEM_TYPE` (`id`),
  CONSTRAINT `FK9sc5qi93p4cby5b2hojcr90gh` FOREIGN KEY (`resourceItemType_id`) REFERENCES `RESOURCE_ITEM_TYPE` (`id`),
  CONSTRAINT `FKs2dv4bd53e7r6vokmm96qh0x4` FOREIGN KEY (`resourceSelection_id`) REFERENCES `PLACE_CONFIG` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DELETE FROM `SCENE_BOT_HARVEST_COMMAND`;
/*!40000 ALTER TABLE `SCENE_BOT_HARVEST_COMMAND` DISABLE KEYS */;
/*!40000 ALTER TABLE `SCENE_BOT_HARVEST_COMMAND` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
