/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE IF NOT EXISTS `SCENE_BOT` (
  `sceneId` int(11) NOT NULL,
  `botd` int(11) NOT NULL,
  UNIQUE KEY `UK_i0h7apnl04b5k9xuifa2j2qcu` (`botd`),
  KEY `FKghhma6f0af1xgwvaq2dqqcm0m` (`sceneId`),
  CONSTRAINT `FK1wawn9gpryikbmh0cjsqel84c` FOREIGN KEY (`botd`) REFERENCES `BOT_CONFIG` (`id`),
  CONSTRAINT `FKghhma6f0af1xgwvaq2dqqcm0m` FOREIGN KEY (`sceneId`) REFERENCES `SCENE` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DELETE FROM `SCENE_BOT`;
/*!40000 ALTER TABLE `SCENE_BOT` DISABLE KEYS */;
INSERT INTO `SCENE_BOT` (`sceneId`, `botd`) VALUES
	(183, 31);
/*!40000 ALTER TABLE `SCENE_BOT` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
