/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE IF NOT EXISTS `SCENE_BOX_ITEM_POSITION` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `x` double NOT NULL,
  `y` double NOT NULL,
  `rotationZ` double NOT NULL,
  `boxItemType_id` int(11) DEFAULT NULL,
  `sceneId` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK1o5uesm507f5p1bu2km3ks769` (`boxItemType_id`),
  KEY `FK3yk9nif0gqotjwm5fmg4ep1ko` (`sceneId`),
  CONSTRAINT `FK1o5uesm507f5p1bu2km3ks769` FOREIGN KEY (`boxItemType_id`) REFERENCES `BOX_ITEM_TYPE` (`id`),
  CONSTRAINT `FK3yk9nif0gqotjwm5fmg4ep1ko` FOREIGN KEY (`sceneId`) REFERENCES `SCENE` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DELETE FROM `SCENE_BOX_ITEM_POSITION`;
/*!40000 ALTER TABLE `SCENE_BOX_ITEM_POSITION` DISABLE KEYS */;
/*!40000 ALTER TABLE `SCENE_BOX_ITEM_POSITION` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
