/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE IF NOT EXISTS `SCENE_START_PLACE_ALLOWED_AREA` (
  `startPointPlacer` int(11) NOT NULL,
  `x` double NOT NULL,
  `y` double NOT NULL,
  `orderColumn` int(11) NOT NULL,
  PRIMARY KEY (`startPointPlacer`,`orderColumn`),
  CONSTRAINT `FKdjbsblqruqfirvx3582gh4hbx` FOREIGN KEY (`startPointPlacer`) REFERENCES `SCENE_START_POINT_PLACER` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DELETE FROM `SCENE_START_PLACE_ALLOWED_AREA`;
/*!40000 ALTER TABLE `SCENE_START_PLACE_ALLOWED_AREA` DISABLE KEYS */;
/*!40000 ALTER TABLE `SCENE_START_PLACE_ALLOWED_AREA` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
