/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE IF NOT EXISTS `SERVER_START_REGION_CONFIG` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `internalName` varchar(255) DEFAULT NULL,
  `minimalLevel_id` int(11) DEFAULT NULL,
  `serverGameEngineId` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FKcx3jju02ngtbbckiw9feme1ll` (`minimalLevel_id`),
  KEY `FKj80ya6k3q8yb33ul57239yuvw` (`serverGameEngineId`),
  CONSTRAINT `FKcx3jju02ngtbbckiw9feme1ll` FOREIGN KEY (`minimalLevel_id`) REFERENCES `LEVEL` (`id`),
  CONSTRAINT `FKj80ya6k3q8yb33ul57239yuvw` FOREIGN KEY (`serverGameEngineId`) REFERENCES `SERVER_GAME_ENGINE_CONFIG` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=62 DEFAULT CHARSET=utf8mb4;

DELETE FROM `SERVER_START_REGION_CONFIG`;
/*!40000 ALTER TABLE `SERVER_START_REGION_CONFIG` DISABLE KEYS */;
INSERT INTO `SERVER_START_REGION_CONFIG` (`id`, `internalName`, `minimalLevel_id`, `serverGameEngineId`) VALUES
	(61, 'Start', 265, 1);
/*!40000 ALTER TABLE `SERVER_START_REGION_CONFIG` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
