/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE IF NOT EXISTS `SERVER_GAME_ENGINE_BOT_CONFIG` (
  `serverGameEngineId` int(11) NOT NULL,
  `botConfigId` int(11) NOT NULL,
  UNIQUE KEY `UK_9w8m9rvbobngldmp0p3hdxgtl` (`botConfigId`),
  KEY `FKh6pao5d5ikcs0h79x6gwx8tfj` (`serverGameEngineId`),
  CONSTRAINT `FKh6pao5d5ikcs0h79x6gwx8tfj` FOREIGN KEY (`serverGameEngineId`) REFERENCES `SERVER_GAME_ENGINE_CONFIG` (`id`),
  CONSTRAINT `FKrlpv849ke6l8gyvfsm5f8ya9g` FOREIGN KEY (`botConfigId`) REFERENCES `BOT_CONFIG` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DELETE FROM `SERVER_GAME_ENGINE_BOT_CONFIG`;
/*!40000 ALTER TABLE `SERVER_GAME_ENGINE_BOT_CONFIG` DISABLE KEYS */;
INSERT INTO `SERVER_GAME_ENGINE_BOT_CONFIG` (`serverGameEngineId`, `botConfigId`) VALUES
	(3, 237);
/*!40000 ALTER TABLE `SERVER_GAME_ENGINE_BOT_CONFIG` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
