/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE IF NOT EXISTS `SERVER_START_REGION_CONFIG_POLYGON` (
  `startRegionConfigEntityId` int(11) NOT NULL,
  `x` double NOT NULL,
  `y` double NOT NULL,
  `orderColumn` int(11) NOT NULL,
  PRIMARY KEY (`startRegionConfigEntityId`,`orderColumn`),
  CONSTRAINT `FKfw2w3t3qbkvhgtnuq99fhclpp` FOREIGN KEY (`startRegionConfigEntityId`) REFERENCES `SERVER_START_REGION_CONFIG` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DELETE FROM `SERVER_START_REGION_CONFIG_POLYGON`;
/*!40000 ALTER TABLE `SERVER_START_REGION_CONFIG_POLYGON` DISABLE KEYS */;
INSERT INTO `SERVER_START_REGION_CONFIG_POLYGON` (`startRegionConfigEntityId`, `x`, `y`, `orderColumn`) VALUES
	(64, 265, 290, 0),
	(64, 266, 290, 1),
	(64, 266, 291, 2);
/*!40000 ALTER TABLE `SERVER_START_REGION_CONFIG_POLYGON` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
