/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE IF NOT EXISTS `SERVER_LEVEL_QUEST` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `internalName` varchar(255) DEFAULT NULL,
  `minimalLevel_id` int(11) DEFAULT NULL,
  `serverGameEngineConfig` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FKmrpwxnx1x6gewn5mhbf9jqux6` (`minimalLevel_id`),
  KEY `FK11joq90eyoabtv4ltmgl6sx5o` (`serverGameEngineConfig`),
  CONSTRAINT `FK11joq90eyoabtv4ltmgl6sx5o` FOREIGN KEY (`serverGameEngineConfig`) REFERENCES `SERVER_GAME_ENGINE_CONFIG` (`id`),
  CONSTRAINT `FKmrpwxnx1x6gewn5mhbf9jqux6` FOREIGN KEY (`minimalLevel_id`) REFERENCES `LEVEL` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8mb4;

DELETE FROM `SERVER_LEVEL_QUEST`;
/*!40000 ALTER TABLE `SERVER_LEVEL_QUEST` DISABLE KEYS */;
INSERT INTO `SERVER_LEVEL_QUEST` (`id`, `internalName`, `minimalLevel_id`, `serverGameEngineConfig`) VALUES
	(14, 'Noob', 265, 3);
/*!40000 ALTER TABLE `SERVER_LEVEL_QUEST` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
