/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE IF NOT EXISTS `SERVER_BOX_REGION_CONFIG` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `count` int(11) NOT NULL,
  `internalName` varchar(255) DEFAULT NULL,
  `maxInterval` int(11) NOT NULL,
  `minDistanceToItems` double NOT NULL,
  `minInterval` int(11) NOT NULL,
  `boxItemTypeId_id` int(11) DEFAULT NULL,
  `region_id` int(11) DEFAULT NULL,
  `serverGameEngineId` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK8i0nxbtvhyiksqd3m90j8sble` (`boxItemTypeId_id`),
  KEY `FKcq7owvwvc3cvnd2dy4b134ed2` (`region_id`),
  KEY `FK4q31xi3o8ty49njgjdolpc5rj` (`serverGameEngineId`),
  CONSTRAINT `FK4q31xi3o8ty49njgjdolpc5rj` FOREIGN KEY (`serverGameEngineId`) REFERENCES `SERVER_GAME_ENGINE_CONFIG` (`id`),
  CONSTRAINT `FK8i0nxbtvhyiksqd3m90j8sble` FOREIGN KEY (`boxItemTypeId_id`) REFERENCES `BOX_ITEM_TYPE` (`id`),
  CONSTRAINT `FKcq7owvwvc3cvnd2dy4b134ed2` FOREIGN KEY (`region_id`) REFERENCES `PLACE_CONFIG` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DELETE FROM `SERVER_BOX_REGION_CONFIG`;
/*!40000 ALTER TABLE `SERVER_BOX_REGION_CONFIG` DISABLE KEYS */;
/*!40000 ALTER TABLE `SERVER_BOX_REGION_CONFIG` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
