/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE IF NOT EXISTS `SERVER_RESOURCE_REGION_CONFIG` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `count` int(11) NOT NULL,
  `internalName` varchar(255) DEFAULT NULL,
  `minDistanceToItems` double NOT NULL,
  `region_id` int(11) DEFAULT NULL,
  `resourceItemType_id` int(11) DEFAULT NULL,
  `serverGameEngineId` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FKrwr42mqa70kps709cr58h2iir` (`region_id`),
  KEY `FKms0li4pxnifye8592vt0yksum` (`resourceItemType_id`),
  KEY `FKm41ytluw6qxyiba2ft8k7p11d` (`serverGameEngineId`),
  CONSTRAINT `FKm41ytluw6qxyiba2ft8k7p11d` FOREIGN KEY (`serverGameEngineId`) REFERENCES `SERVER_GAME_ENGINE_CONFIG` (`id`),
  CONSTRAINT `FKms0li4pxnifye8592vt0yksum` FOREIGN KEY (`resourceItemType_id`) REFERENCES `RESOURCE_ITEM_TYPE` (`id`),
  CONSTRAINT `FKrwr42mqa70kps709cr58h2iir` FOREIGN KEY (`region_id`) REFERENCES `PLACE_CONFIG` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=81 DEFAULT CHARSET=utf8mb4;

DELETE FROM `SERVER_RESOURCE_REGION_CONFIG`;
/*!40000 ALTER TABLE `SERVER_RESOURCE_REGION_CONFIG` DISABLE KEYS */;
INSERT INTO `SERVER_RESOURCE_REGION_CONFIG` (`id`, `count`, `internalName`, `minDistanceToItems`, `region_id`, `resourceItemType_id`, `serverGameEngineId`) VALUES
	(79, 5, 'Start', 0, 564, 2, 1),
	(80, 5, 'Gigantism', 0, 565, 2, 1);
/*!40000 ALTER TABLE `SERVER_RESOURCE_REGION_CONFIG` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
