/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE IF NOT EXISTS `SERVER_GAME_ENGINE_BOT_SCENE_CONFIG` (
  `serverGameEngineId` int(11) NOT NULL,
  `botSceneConfigId` int(11) NOT NULL,
  UNIQUE KEY `UK_rusfme732vodwo2j02s27oxhp` (`botSceneConfigId`),
  KEY `FK80dfty4j4too59uh1t4axhmt9` (`serverGameEngineId`),
  CONSTRAINT `FK2bm7mr807eoedkfin3pf4mamb` FOREIGN KEY (`botSceneConfigId`) REFERENCES `BOT_SCENE_CONFIG` (`id`),
  CONSTRAINT `FK80dfty4j4too59uh1t4axhmt9` FOREIGN KEY (`serverGameEngineId`) REFERENCES `SERVER_GAME_ENGINE_CONFIG` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DELETE FROM `SERVER_GAME_ENGINE_BOT_SCENE_CONFIG`;
/*!40000 ALTER TABLE `SERVER_GAME_ENGINE_BOT_SCENE_CONFIG` DISABLE KEYS */;
/*!40000 ALTER TABLE `SERVER_GAME_ENGINE_BOT_SCENE_CONFIG` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
