/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE IF NOT EXISTS `TERRAIN_SLOPE_POSITION` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `inverted` bit(1) NOT NULL,
  `slopeConfigEntity_id` int(11) NOT NULL,
  `parentTerrainSlopePosition` int(11) DEFAULT NULL,
  `planet` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK4xqtrjsn0gheqg5og8e9s5mmt` (`slopeConfigEntity_id`),
  KEY `FKmhab0g7928t6vw57a79a17pn5` (`parentTerrainSlopePosition`),
  KEY `FK5ptx8wbuewvwsgwc7uom195h0` (`planet`),
  CONSTRAINT `FK4xqtrjsn0gheqg5og8e9s5mmt` FOREIGN KEY (`slopeConfigEntity_id`) REFERENCES `SLOPE_CONFIG` (`id`),
  CONSTRAINT `FK5ptx8wbuewvwsgwc7uom195h0` FOREIGN KEY (`planet`) REFERENCES `PLANET` (`id`),
  CONSTRAINT `FKmhab0g7928t6vw57a79a17pn5` FOREIGN KEY (`parentTerrainSlopePosition`) REFERENCES `TERRAIN_SLOPE_POSITION` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=26 DEFAULT CHARSET=utf8mb4;

DELETE FROM `TERRAIN_SLOPE_POSITION`;
/*!40000 ALTER TABLE `TERRAIN_SLOPE_POSITION` DISABLE KEYS */;
INSERT INTO `TERRAIN_SLOPE_POSITION` (`id`, `inverted`, `slopeConfigEntity_id`, `parentTerrainSlopePosition`, `planet`) VALUES
	(1, b'0', 1, NULL, 117),
	(20, b'0', 22, NULL, 117),
	(21, b'0', 1, NULL, 117),
	(22, b'0', 1, 21, NULL),
	(23, b'0', 23, 21, NULL),
	(25, b'0', 25, 21, NULL);
/*!40000 ALTER TABLE `TERRAIN_SLOPE_POSITION` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
