/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE IF NOT EXISTS `THREE_JS_MODEL_PACK` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `internalName` varchar(255) DEFAULT NULL,
  `positionX` double DEFAULT NULL,
  `positionY` double DEFAULT NULL,
  `positionZ` double DEFAULT NULL,
  `rotationX` double DEFAULT NULL,
  `rotationY` double DEFAULT NULL,
  `rotationZ` double DEFAULT NULL,
  `scaleX` double DEFAULT NULL,
  `scaleY` double DEFAULT NULL,
  `scaleZ` double DEFAULT NULL,
  `threeJsModelConfig_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK1odbqn8a5lg9edjr451fi17hf` (`threeJsModelConfig_id`),
  CONSTRAINT `FK1odbqn8a5lg9edjr451fi17hf` FOREIGN KEY (`threeJsModelConfig_id`) REFERENCES `THREE_JS_MODEL` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=134 DEFAULT CHARSET=utf8mb4;

DELETE FROM `THREE_JS_MODEL_PACK`;
/*!40000 ALTER TABLE `THREE_JS_MODEL_PACK` DISABLE KEYS */;
INSERT INTO `THREE_JS_MODEL_PACK` (`id`, `internalName`, `positionX`, `positionY`, `positionZ`, `rotationX`, `rotationY`, `rotationZ`, `scaleX`, `scaleY`, `scaleZ`, `threeJsModelConfig_id`) VALUES
	(30, 'Building 01', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 47),
	(31, 'Building 02', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 47),
	(82, 'Rock1_grup2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 48),
	(84, 'Rock1_grup4', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 48),
	(85, 'Rock1D', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 48),
	(86, 'Rock1C', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 48),
	(87, 'Rock1A', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 48),
	(88, 'Rock1B', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 48),
	(89, 'Rock1_grup5', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 48),
	(90, 'Rock1E', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 48),
	(91, 'Rock1LOD_grup5', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 48),
	(92, 'Rock1LOD_grup4', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 48),
	(94, 'Rock1LOD_grup3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 48),
	(96, 'Rock2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 48),
	(97, 'Rock4B', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 48),
	(98, 'Rock5A', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 48),
	(99, 'Rock3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 48),
	(100, 'Rock5B', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 48),
	(101, 'Rock4A', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 48),
	(102, 'Rock6A', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 48),
	(103, 'Rock6C', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 48),
	(104, 'Rock6B', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 48),
	(105, 'banana_plant', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 49),
	(107, 'banana_plant_small', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 49),
	(108, 'fern', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 49),
	(109, 'fern_small', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 49),
	(110, 'palm_bush', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 49),
	(112, 'palm_tree', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 49),
	(114, 'palm_tree2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 49),
	(115, 'tropical_fern', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 49),
	(116, 'tropical_plant', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 49),
	(117, 'Building_01', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 47),
	(118, 'Building_02', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 47),
	(119, 'Building_03', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 47),
	(121, 'Building_05', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 47),
	(122, 'Building_06', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 47),
	(124, 'Building_08', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 47),
	(126, 'Building_12', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 47),
	(127, 'Building_10', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 47),
	(128, 'Building_11', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 47),
	(129, 'Building_14', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 47),
	(130, 'Building_13', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 47),
	(131, 'Building_15', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 47),
	(132, 'Building_16', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 47),
	(133, 'PilhaCristal3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 52);
/*!40000 ALTER TABLE `THREE_JS_MODEL_PACK` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
