/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `BASE_ITEM_TYPE` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `acceleration` double DEFAULT NULL,
  `angularVelocity` double DEFAULT NULL,
  `boxPickupRange` double NOT NULL,
  `buildup` int(11) NOT NULL,
  `dropBoxPossibility` double NOT NULL,
  `explosionParticleConfigId_TMP` int(11) DEFAULT NULL,
  `fixVerticalNorm` bit(1) NOT NULL,
  `health` int(11) NOT NULL,
  `internalName` varchar(255) DEFAULT NULL,
  `price` int(11) NOT NULL,
  `radius` double NOT NULL,
  `spawnDurationMillis` int(11) NOT NULL,
  `speed` double DEFAULT NULL,
  `terrainType` varchar(255) DEFAULT NULL,
  `unlockCrystals` int(11) DEFAULT NULL,
  `xpOnKilling` int(11) NOT NULL,
  `builderType_id` int(11) DEFAULT NULL,
  `buildupTexture_id` int(11) DEFAULT NULL,
  `consumerType_id` int(11) DEFAULT NULL,
  `demolitionImage_id` int(11) DEFAULT NULL,
  `dropBoxItemTypeEntity_id` int(11) DEFAULT NULL,
  `factoryType_id` int(11) DEFAULT NULL,
  `generatorType_id` int(11) DEFAULT NULL,
  `harvesterType_id` int(11) DEFAULT NULL,
  `houseType_id` int(11) DEFAULT NULL,
  `i18nDescription_id` int(11) DEFAULT NULL,
  `i18nName_id` int(11) DEFAULT NULL,
  `itemContainerType_id` int(11) DEFAULT NULL,
  `shape3DId_id` int(11) DEFAULT NULL,
  `spawnAudio_id` int(11) DEFAULT NULL,
  `spawnShape3DId_id` int(11) DEFAULT NULL,
  `specialType_id` int(11) DEFAULT NULL,
  `thumbnail_id` int(11) DEFAULT NULL,
  `weaponType_id` int(11) DEFAULT NULL,
  `wreckageShape3D_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FKm7s2waq0lu64mpcrkd9jk521r` (`builderType_id`),
  KEY `FKtfr9577qfkq3ejl5gy2tbs1c0` (`buildupTexture_id`),
  KEY `FKewwopla27f0l5uuo7c111c6vx` (`consumerType_id`),
  KEY `FK5stwq1bmxsf4gfbax7tt1c1g5` (`demolitionImage_id`),
  KEY `FKsgd0elhjg8fo41g1tcjxq4390` (`dropBoxItemTypeEntity_id`),
  KEY `FKma6w4ce90clwtx027b80i3tae` (`factoryType_id`),
  KEY `FK7hhfbb8cnjrhyul76r05u8cdo` (`generatorType_id`),
  KEY `FKtj1i80eadv6cr8ydynl1kc39s` (`harvesterType_id`),
  KEY `FK5popx7pvso0sp3jdqhj1lwutn` (`houseType_id`),
  KEY `FKqdr3dh30y7eaywu60npthmh1i` (`i18nDescription_id`),
  KEY `FKdc6o3q4w1ni0a5hclsdq068u7` (`i18nName_id`),
  KEY `FKhm9xqu5a5dpv41x44vow0no6p` (`itemContainerType_id`),
  KEY `FKjjxk2oxiywyjc4mjhbn2esi5m` (`shape3DId_id`),
  KEY `FK2fd7inmdsi02vom6uk8nr179h` (`spawnAudio_id`),
  KEY `FKsk0soitdh85fl3i9dbxu32hgp` (`spawnShape3DId_id`),
  KEY `FKtog0l4xkcmxs3pgybiph2v4a9` (`specialType_id`),
  KEY `FKcdywk1gvxhj7ph9vjjltltqoc` (`thumbnail_id`),
  KEY `FKm18curnkip5ya1dnsngfe0amv` (`weaponType_id`),
  KEY `FKpfw7lsvxtvnuwy6gj6u09wclc` (`wreckageShape3D_id`),
  CONSTRAINT `FK2fd7inmdsi02vom6uk8nr179h` FOREIGN KEY (`spawnAudio_id`) REFERENCES `AUDIO_LIBRARY` (`id`),
  CONSTRAINT `FK5popx7pvso0sp3jdqhj1lwutn` FOREIGN KEY (`houseType_id`) REFERENCES `BASE_ITEM_HOUSE_TYPE` (`id`),
  CONSTRAINT `FK5stwq1bmxsf4gfbax7tt1c1g5` FOREIGN KEY (`demolitionImage_id`) REFERENCES `IMAGE_LIBRARY` (`id`),
  CONSTRAINT `FK7hhfbb8cnjrhyul76r05u8cdo` FOREIGN KEY (`generatorType_id`) REFERENCES `BASE_ITEM_GENERATOR_TYPE` (`id`),
  CONSTRAINT `FKcdywk1gvxhj7ph9vjjltltqoc` FOREIGN KEY (`thumbnail_id`) REFERENCES `IMAGE_LIBRARY` (`id`),
  CONSTRAINT `FKdc6o3q4w1ni0a5hclsdq068u7` FOREIGN KEY (`i18nName_id`) REFERENCES `I18N_BUNDLE` (`id`),
  CONSTRAINT `FKewwopla27f0l5uuo7c111c6vx` FOREIGN KEY (`consumerType_id`) REFERENCES `BASE_ITEM_CONSUMER_TYPE` (`id`),
  CONSTRAINT `FKhm9xqu5a5dpv41x44vow0no6p` FOREIGN KEY (`itemContainerType_id`) REFERENCES `BASE_ITEM_ITEM_CONTAINER_TYPE` (`id`),
  CONSTRAINT `FKjjxk2oxiywyjc4mjhbn2esi5m` FOREIGN KEY (`shape3DId_id`) REFERENCES `COLLADA` (`id`),
  CONSTRAINT `FKm18curnkip5ya1dnsngfe0amv` FOREIGN KEY (`weaponType_id`) REFERENCES `BASE_ITEM_WEAPON_TYPE` (`id`),
  CONSTRAINT `FKm7s2waq0lu64mpcrkd9jk521r` FOREIGN KEY (`builderType_id`) REFERENCES `BASE_ITEM_BUILDER_TYPE` (`id`),
  CONSTRAINT `FKma6w4ce90clwtx027b80i3tae` FOREIGN KEY (`factoryType_id`) REFERENCES `BASE_ITEM_FACTORY_TYPE` (`id`),
  CONSTRAINT `FKpfw7lsvxtvnuwy6gj6u09wclc` FOREIGN KEY (`wreckageShape3D_id`) REFERENCES `COLLADA` (`id`),
  CONSTRAINT `FKqdr3dh30y7eaywu60npthmh1i` FOREIGN KEY (`i18nDescription_id`) REFERENCES `I18N_BUNDLE` (`id`),
  CONSTRAINT `FKsgd0elhjg8fo41g1tcjxq4390` FOREIGN KEY (`dropBoxItemTypeEntity_id`) REFERENCES `BOX_ITEM_TYPE` (`id`),
  CONSTRAINT `FKsk0soitdh85fl3i9dbxu32hgp` FOREIGN KEY (`spawnShape3DId_id`) REFERENCES `COLLADA` (`id`),
  CONSTRAINT `FKtfr9577qfkq3ejl5gy2tbs1c0` FOREIGN KEY (`buildupTexture_id`) REFERENCES `IMAGE_LIBRARY` (`id`),
  CONSTRAINT `FKtj1i80eadv6cr8ydynl1kc39s` FOREIGN KEY (`harvesterType_id`) REFERENCES `BASE_ITEM_HARVESTER_TYPE` (`id`),
  CONSTRAINT `FKtog0l4xkcmxs3pgybiph2v4a9` FOREIGN KEY (`specialType_id`) REFERENCES `BASE_ITEM_SPECIAL_TYPE` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=22 DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

