version: '3'

services:
  db:
    image: mariadb
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: razarion
      MYSQL_USER: raz_user
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "32788:3306"
    command: [
      '--wait_timeout=28800',
      '--max_allowed_packet=200000000'
    ]
  #  db_system_test:
  #    image: mariadb
  #    container_name: db_system_test
  #    restart: always
  #    environment:
  #      MYSQL_DATABASE: razarion
  #      MYSQL_USER: raz_user
  #      MYSQL_PASSWORD: 1234
  #      MYSQL_ROOT_PASSWORD: 1234
  #    ports:
  #      - "32788:3306"
  #    command: [
  #      '--wait_timeout=28800',
  #      '--max_allowed_packet=200000000'
  #    ]

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"   # SMTP port
      - "8025:8025"   # Web UI http://localhost:8025/#
